### PR TITLE
Support for bootstrap in Horizon

### PR DESCRIPTION
**Pull request by randybertram**

### CODE REVIEW

**Comment by dkavanagh** [comment]
I wanted to ask about bootstrap and icons. There are some fi-\* icons uses which come from foundation. If we have a bootstrap version of the html file, should that use icons from http://glyphicons.bootstrapcheatsheets.com/ ?
I see a .glyphicon-filter and .glyphicon-remove that would work.

**Comment by randybertram** [comment]
Yes, that's how it works. Look at this file to see what I'm doing:
https://review.openstack.org/#/c/151386/14/openstack_dashboard/static/dashboard/scss/horizon.scss
You can see that .fi-filter is defined to .fa-filter, and .fi-x
is .fa-times.
Another reasonable approach would be to specify both styles, and let the
inappropriate one get ignored.

Suggest you look through all these styles, and see if you have better
ideas.

Do you have an account on PyPI? If not, can you get one? I will make you a
co-owner of the XStatic patch.

Randy Bertram
STSM - UI Architect
Cloud Systems Software Development

 Phone: 919-543-8715 | Tie-Line: 441-8715  
 E-mail: rbertram@us.ibm.com  
                                               3039 E Cornwallis Rd 
                                            Research Triangle Park, 
                                                      NC 27709-2195 
                                                      United States

**Comment by dkavanagh** [comment]
I've created an account as "dkavanagh" on pypi

**Comment by dkavanagh** [comment]
The thought I had with bootstrap icons right in the html was that the widget would be more quickly useful to another project using bootstrap without pulling in some css from horizon.

**Comment by randybertram** [comment]
you're an owner

Randy Bertram
STSM - UI Architect
Cloud Systems Software Development

 Phone: 919-543-8715 | Tie-Line: 441-8715  
 E-mail: rbertram@us.ibm.com  
                                               3039 E Cornwallis Rd 
                                            Research Triangle Park, 
                                                      NC 27709-2195 
                                                      United States

**Comment by randybertram** [comment]
I have updated xstatic and the pull-request with your suggestion to include the bootstrap styles directly in the html. You should try the result, and make sure it still works in Eucalyptus.

**Comment by dkavanagh** [comment]
Looks good. I pulled in the updated html and js files and did some testing in Eucalyptus with good results.

**Pull request merged**
